from __future__ import annotations

import logging
from pathlib import Path

from styleclaw.core.image_utils import build_image_block
from styleclaw.core.models import ModelEvaluation
from styleclaw.core.text_utils import parse_llm_response
from styleclaw.providers.llm.base import LLMProvider

logger = logging.getLogger(__name__)

PROMPT_TEMPLATE_PATH = Path(__file__).parent.parent / "providers" / "llm" / "prompts" / "select_model.md"


async def evaluate_models(
    llm: LLMProvider,
    ref_image_paths: list[Path],
    model_images: dict[str, list[Path]],
) -> ModelEvaluation:
    system_prompt = PROMPT_TEMPLATE_PATH.read_text(encoding="utf-8")

    content: list[dict] = []

    content.append({"type": "text", "text": "## Reference Images"})
    content.extend(build_image_block(p) for p in ref_image_paths)

    for key, images in model_images.items():
        if "/" in key:
            model_id, variant = key.split("/", 1)
            label = f"{model_id} [{variant}]"
        else:
            label = key
        content.append({"type": "text", "text": f"## Generated by: {label}"})
        content.extend(build_image_block(p) for p in images)

    content.append({
        "type": "text",
        "text": "Score each model×variant combination against the reference images. "
        "Compare prompt-only vs prompt-sref for each model.",
    })

    messages = [{"role": "user", "content": content}]
    raw = await llm.invoke(system=system_prompt, messages=messages, max_tokens=4096)

    evaluation = parse_llm_response(raw, ModelEvaluation, "model evaluation")
    logger.info("Model evaluation complete. Recommendation: %s", evaluation.recommendation)
    return evaluation
