from __future__ import annotations

import json
import logging
from pathlib import Path

from styleclaw.core.image_utils import encode_image_for_llm
from styleclaw.core.models import ModelEvaluation
from styleclaw.core.text_utils import clean_json
from styleclaw.providers.llm.base import LLMProvider

logger = logging.getLogger(__name__)

PROMPT_TEMPLATE_PATH = Path(__file__).parent.parent / "providers" / "llm" / "prompts" / "select_model.md"


async def evaluate_models(
    llm: LLMProvider,
    ref_image_paths: list[Path],
    model_images: dict[str, list[Path]],
) -> ModelEvaluation:
    system_prompt = PROMPT_TEMPLATE_PATH.read_text(encoding="utf-8")

    content: list[dict] = []

    content.append({"type": "text", "text": "## Reference Images"})
    for img_path in ref_image_paths:
        b64_data, mt = encode_image_for_llm(img_path)
        content.append({
            "type": "image",
            "source": {"type": "base64", "media_type": mt, "data": b64_data},
        })

    for model_id, images in model_images.items():
        content.append({"type": "text", "text": f"## Generated by: {model_id}"})
        for img_path in images:
            b64_data, mt = encode_image_for_llm(img_path)
            content.append({
                "type": "image",
                "source": {"type": "base64", "media_type": mt, "data": b64_data},
            })

    content.append({
        "type": "text",
        "text": "Score each model's output against the reference images.",
    })

    messages = [{"role": "user", "content": content}]
    raw = await llm.invoke(system=system_prompt, messages=messages, max_tokens=4096)

    cleaned = clean_json(raw)
    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError as exc:
        raise ValueError(f"LLM returned invalid JSON for model evaluation: {exc}") from exc
    try:
        evaluation = ModelEvaluation.model_validate(data)
    except Exception as exc:
        raise ValueError(f"LLM response failed validation for ModelEvaluation: {exc}") from exc
    logger.info("Model evaluation complete. Recommendation: %s", evaluation.recommendation)
    return evaluation
