from __future__ import annotations

import logging
from pathlib import Path

from styleclaw.core.image_utils import build_image_block
from styleclaw.core.models import ModelEvaluation
from styleclaw.core.text_utils import parse_llm_response
from styleclaw.providers.llm.base import LLMProvider

logger = logging.getLogger(__name__)

PROMPT_TEMPLATE_PATH = Path(__file__).parent.parent / "providers" / "llm" / "prompts" / "select_model.md"


def _build_system_prompt() -> str:
    return PROMPT_TEMPLATE_PATH.read_text(encoding="utf-8")


def _build_messages(
    ref_image_paths: list[Path],
    model_images: dict[str, list[Path]],
) -> list[dict]:
    content: list[dict] = [{"type": "text", "text": "## Reference Images"}]
    content.extend(build_image_block(p) for p in ref_image_paths)
    for key, images in model_images.items():
        if "/" in key:
            model_id, variant = key.split("/", 1)
            label = f"{model_id} [{variant}]"
        else:
            label = key
        content.append({"type": "text", "text": f"## Generated by: {label}"})
        content.extend(build_image_block(p) for p in images)
    content.append({
        "type": "text",
        "text": "Score each model×variant combination against the reference images. "
        "Compare prompt-only vs prompt-sref for each model.",
    })
    return [{"role": "user", "content": content}]


def _parse_evaluation(raw_text: str) -> ModelEvaluation:
    return parse_llm_response(raw_text, ModelEvaluation, "model evaluation")


async def evaluate_models(
    llm: LLMProvider,
    ref_image_paths: list[Path],
    model_images: dict[str, list[Path]],
) -> ModelEvaluation:
    raw = await llm.invoke(
        system=_build_system_prompt(),
        messages=_build_messages(ref_image_paths, model_images),
        max_tokens=4096,
    )
    evaluation = _parse_evaluation(raw)
    logger.info("Model evaluation complete. Recommendation: %s", evaluation.recommendation)
    return evaluation


async def evaluate_models_with_thinking(
    llm: LLMProvider,
    ref_image_paths: list[Path],
    model_images: dict[str, list[Path]],
    thinking_budget: int = 5000,
) -> tuple[ModelEvaluation, str]:
    response = await llm.invoke_with_thinking(
        system=_build_system_prompt(),
        messages=_build_messages(ref_image_paths, model_images),
        max_tokens=4096,
        thinking_budget=thinking_budget,
    )
    evaluation = _parse_evaluation(response.text)
    logger.info(
        "Model evaluation (with thinking) complete. Recommendation: %s",
        evaluation.recommendation,
    )
    return evaluation, response.thinking
